version: '3.8'

services:
  # Broker MQTT
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker_deuxexmachina
    restart: unless-stopped
    ports:
      - "1883:1883" # Porta padrão MQTT
      # - "9001:9001" # Para MQTT sobre WebSockets, se precisar
    volumes:
      # Opcional: para configurações customizadas e persistência de dados do Mosquitto
      # - ./mosquitto/config:/mosquitto/config
      # - ./mosquitto/data:/mosquitto/data
      # - ./mosquitto/log:/mosquitto/log
    networks:
      - deuxexmachina_net

  # Primeira IA do Pipeline
  ia_processamento_1:
    build:
      context: ./ia_processamento_1 # Diretório que você vai criar para esta IA
      dockerfile: Dockerfile
    container_name: ia_processamento_1_service
    restart: unless-stopped
    environment:
      - MQTT_BROKER_HOST=mqtt # Nome do serviço do broker na rede Docker
      - MQTT_BROKER_PORT=1883
      - INPUT_TOPIC=pipeline/entrada_requisicoes
      - OUTPUT_TOPIC=pipeline/saida_ia1
      - PYTHONUNBUFFERED=1 # Para ver logs do Python imediatamente
    depends_on:
      - mqtt # Garante que o MQTT inicie antes desta IA
    networks:
      - deuxexmachina_net

  # Opcional, mas recomendado para testes iniciais: Node-RED
  nodered:
    image: nodered/node-red:latest
    container_name: nodered_deuxexmachina
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data # Para persistir seus fluxos
    environment:
      - TZ=America/Sao_Paulo #
    depends_on:
      - mqtt
    networks:
      - deuxexmachina_net

networks:
  deuxexmachina_net:
    driver: bridge